module.exports = {
  public: [
    'NEXT_PUBLIC_API_HOST',
    'NEXT_PUBLIC_JWT_EXPIRATION_IN_HOURS',
    'NEXT_PUBLIC_ENABLE_CONSOLE_LOG',
    'NEXT_PUBLIC_ENABLE_CONSOLE_LOG_KEY',
    'NEXT_PUBLIC_GOOGLE_API_KEY',
  ],
  server: [
    'NEXT_PUBLIC_API_HOST',
    'NEXT_PUBLIC_JWT_EXPIRATION_IN_HOURS',
    'NEXT_PUBLIC_ENABLE_CONSOLE_LOG',
    'NEXT_PUBLIC_ENABLE_CONSOLE_LOG_KEY',
    'NEXT_PUBLIC_GOOGLE_API_KEY',
  ],
};
